name: E2E - Cypress (Web + Chatbot)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    environment: ORANGEHRM_USER   # <- usa el Environment donde guardaste los secrets

    env:
      CYPRESS_ORANGEHRM_USER: ${{ secrets.ORANGEHRM_USER }}
      CYPRESS_ORANGEHRM_PASS: ${{ secrets.ORANGEHRM_PASS }}
      CYPRESS_CHATBOT_URL:    ${{ secrets.CHATBOT_URL }}
      CYPRESS_retries: 2

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - run: npm ci
      - uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
          command: >
            npx cypress run
            --browser chrome
            --reporter junit
            --reporter-options "mochaFile=reports/junit/results-[hash].xml,toConsole=true"
            --spec "cypress/e2e/orangehrm/**/*.cy.js,cypress/e2e/chatbot/**/*.cy.js"
      - if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Cypress JUnit
          path: reports/junit/**/*.xml
          reporter: java-junit
          fail-on-empty: false
      - if: always()
        uses: actions/upload-artifact@v4
        with: { name: cypress-videos, path: cypress/videos, if-no-files-found: ignore }
      - if: always()
        uses: actions/upload-artifact@v4
        with: { name: cypress-screenshots, path: cypress/screenshots, if-no-files-found: ignore }